# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_range', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=10)),
                ('comp_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Oneplus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('model_no', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=150000)),
                ('ram', models.CharField(max_length=10)),
                ('album_logo', models.CharField(max_length=1000)),
                ('is_favorite', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Company')),
            ],
        ),
    ]
