# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('doorno', models.CharField(max_length=20, null=True)),
                ('streetname', models.CharField(max_length=100, null=True)),
                ('locality', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
