# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
