# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('doorno', models.CharField(max_length=20)),
                ('streetname', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
