# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_addressform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressForm',
        ),
    ]
