# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
