# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_asus_google_huawei_lenovo_motorola_sony'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Huawei',
            new_name='LG',
        ),
    ]
