# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_queryget'),
    ]

    operations = [
        migrations.AddField(
            model_name='apple',
            name='stock',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='asus',
            name='stock',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='google',
            name='stock',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='lenovo',
            name='stock',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='lg',
            name='stock',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='motorola',
            name='stock',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='oneplus',
            name='stock',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='samsung',
            name='stock',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='sony',
            name='stock',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='xiaomi',
            name='stock',
            field=models.IntegerField(default=100),
        ),
    ]
