# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_usercredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredit',
            name='credit',
            field=models.FloatField(default=0.0),
        ),
    ]
